version: '2.1'

services:
  lininfo: 
    image: mortalbm/lininfo:v1.0
    container_name: lininfo
    restart: unless-stopped
    expose:
      - 5000
  
  caddy:
    image: caddy:2.6.4
    container_name: caddy
    ports:
      - "5000:443"
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO}
    restart: unless-stopped